/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/documents': typeof DocumentsRoute
  '/notes': typeof NotesRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/summaries': typeof SummariesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/documents': typeof DocumentsRoute
  '/notes': typeof NotesRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/summaries': typeof SummariesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/documents': typeof DocumentsRoute
  '/notes': typeof NotesRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/summaries': typeof SummariesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/documents'
    | '/notes'
    | '/quiz'
    | '/settings'
    | '/summaries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/documents'
    | '/notes'
    | '/quiz'
    | '/settings'
    | '/summaries'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/documents'
    | '/notes'
    | '/quiz'
    | '/settings'
    | '/summaries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DocumentsRoute: typeof DocumentsRoute
  NotesRoute: typeof NotesRoute
  QuizRoute: typeof QuizRoute
  SettingsRoute: typeof SettingsRoute
  SummariesRoute: typeof SummariesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DocumentsRoute: DocumentsRoute,
  NotesRoute: NotesRoute,
  QuizRoute: QuizRoute,
  SettingsRoute: SettingsRoute,
  SummariesRoute: SummariesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
